initial_feedbacks = [
    {
        "name": "Arjun Mehta",
        "department": "Computer Science & Engineering",
        "problems": ["Food / Mess / Canteen"],
        "frequency": "Daily",
        "affected": "Students",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Website Portal", "Booking / Scheduling System"],
        "user_group": "Students",
        "description": "The queue at the canteen during lunch hours is extremely long. A digital ordering/booking portal would allow students to preorder food and reduce the crowd size.",
        "priority": "Medium",
        "status": "In Progress",
        "solution_name": "Canteen Pre-Order & Booking Portal",
        "solution_type": "Website Portal",
        "solution_status": "Deployed",
        "solution_description": "An online menu and pre-ordering web portal enabling students to purchase lunch slots in advance and skip the main queues."
    },
    {
        "name": "Priya Sharma",
        "department": "Electrical Engineering",
        "problems": ["Infrastructure (classroom, lab, hostel, washroom, etc.)"],
        "frequency": "Daily",
        "affected": "Everyone",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Chatbot / Helpdesk", "QR-based System"],
        "user_group": "Both",
        "description": "The washroom on the 2nd floor of Block A is constantly lacking water and soap. A QR-based quick reporting system on the washroom door could help trigger maintenance alerts automatically.",
        "priority": "High",
        "status": "Pending",
        "solution_name": "QR Restroom Alert System",
        "solution_type": "QR-based System",
        "solution_status": "In Development",
        "solution_description": "Custom scan codes placed in all public restrooms that trigger high-priority maintenance requests directly to cleaning teams."
    },
    {
        "name": "Rohan Das",
        "department": "Mechanical Engineering",
        "problems": ["Internet / Wi-Fi"],
        "frequency": "Weekly",
        "affected": "Students",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Notification / Alert System"],
        "user_group": "Both",
        "description": "Library Wi-Fi frequently disconnects after 4 PM, especially near the study desks. We need a live notification system or status page showing Wi-Fi load and uptime.",
        "priority": "High",
        "status": "Resolved",
        "solution_name": "Library Wi-Fi Load Monitor",
        "solution_type": "Website Portal",
        "solution_status": "Deployed",
        "solution_description": "A web dashboard integrated with the library APs showing real-time load and alerting students on high latency zones."
    },
    {
        "name": "Dr. Amit Verma",
        "department": "Physics",
        "problems": ["Administration / Paperwork"],
        "frequency": "Occasionally",
        "affected": "Faculty",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Website Portal"],
        "user_group": "Admin/Staff",
        "description": "Reimbursement claims for academic materials require printing physical forms and manually walking them to the finance office. Implementing a scanned PDF approval portal would save weeks of processing time.",
        "priority": "Low",
        "status": "In Progress",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Sneha Reddy",
        "department": "Information Technology",
        "problems": ["Safety / Security"],
        "frequency": "Daily",
        "affected": "Everyone",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Mobile App", "Notification / Alert System"],
        "user_group": "Both",
        "description": "Streetlights from the science block to the hostel gates are broken and off for a week. Walking there at night feels unsafe. An emergency alert button on the campus app would help security staff track patrols.",
        "priority": "High",
        "status": "Pending",
        "solution_name": "Campus Forest SafeNav App",
        "solution_type": "Mobile App",
        "solution_status": "In Development",
        "solution_description": "An offline companion map app showing lighted trails, safety escort requests, and hazards (such as broken streetlights) for student navigation."
    },
    {
        "name": "Vikram Malhotra",
        "department": "Business School",
        "problems": ["Mental Health / Wellbeing"],
        "frequency": "Occasionally",
        "affected": "Students",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Chatbot / Helpdesk", "Booking / Scheduling System"],
        "user_group": "Students",
        "description": "Getting counselor appointments is highly intimidating because you have to walk in physically to book. An anonymous scheduling portal would make it much easier for students in crisis to seek guidance.",
        "priority": "Medium",
        "status": "Resolved",
        "solution_name": "MindCare Booking Portal",
        "solution_type": "Booking / Scheduling System",
        "solution_status": "Deployed",
        "solution_description": "An anonymous booking system that provides encrypted slot selection for counseling appointments without sharing personal data."
    },
    {
        "name": "Prof. Sarah John",
        "department": "Chemistry",
        "problems": ["Infrastructure (classroom, lab, hostel, washroom, etc.)", "Faculty / Teaching"],
        "frequency": "Weekly",
        "affected": "Faculty",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Notification / Alert System"],
        "user_group": "Both",
        "description": "Projectors in Hall 3 keep flickering and shutting down mid-lecture. It disrupts classes consistently. Need an alert/ticket system to report IT issues instantly.",
        "priority": "Medium",
        "status": "Pending",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Anonymous",
        "department": "Civil Engineering",
        "problems": ["Faculty / Teaching"],
        "frequency": "Rarely / One-time",
        "affected": "Students",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Students",
        "description": "Assignment feedback for the mid-semester paper was only given as a letter grade without any comments or guidance. It makes it very hard to know how to improve for the finals.",
        "priority": "Low",
        "status": "Pending",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    }
]
