initial_feedbacks = [
    {
        "name": "Priya Ramesh",
        "student_name": "Arjun Ramesh",
        "department": "Guduvancheri",
        "branch": "Guduvancheri",
        "problems": ["Appreciation"],
        "feedback_category": "Appreciation",
        "star_rating": 5,
        "main_feedback": "My son has improved so much in violin since joining KFA. The teacher is very patient and explains everything clearly. We are very happy with the progress.",
        "improvement_areas": ["Events", "Exams"],
        "expectations": "We would love to see more student performance events and annual day celebrations. It motivates children a lot.",
        "recommend": "Yes",
        "additional_comments": "Please keep the current violin teacher. She is excellent.",
        "contact_preference": "No",
        "phone_number": "",
        "frequency": "Occasionally",
        "affected": "Students",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Students",
        "description": "Very happy with the overall teaching quality and staff behaviour.",
        "priority": "Low",
        "status": "Resolved",
        "feedback_id": "KFA-2026-100001",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Mohammed Ismail",
        "student_name": "Aisha Ismail",
        "department": "Madambakkam",
        "branch": "Madambakkam",
        "problems": ["Complaint"],
        "feedback_category": "Complaint",
        "star_rating": 2,
        "main_feedback": "The waiting area for parents is very small and has no fan or air conditioning. During summer it becomes very uncomfortable to wait for 45 minutes.",
        "improvement_areas": ["Waiting Area", "Facilities"],
        "expectations": "Please add at least a ceiling fan and some chairs in the waiting area. Parents wait long time outside.",
        "recommend": "Maybe",
        "additional_comments": "Other than the waiting area issue, the teaching is good.",
        "contact_preference": "Yes",
        "phone_number": "9876543210",
        "frequency": "Daily",
        "affected": "Everyone",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Both",
        "description": "Waiting area needs improvement urgently.",
        "priority": "High",
        "status": "New",
        "feedback_id": "KFA-2026-100002",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Lakshmi Subramaniam",
        "student_name": "Karthik Subramaniam",
        "department": "Guduvancheri",
        "branch": "Guduvancheri",
        "problems": ["Suggestion"],
        "feedback_category": "Suggestion",
        "star_rating": 4,
        "main_feedback": "It would be great if KFA could send a weekly progress update via WhatsApp. We don't always get to talk to the teacher during pickup.",
        "improvement_areas": ["Communication", "Teaching"],
        "expectations": "A monthly parent-teacher meeting would help us understand how our child is progressing.",
        "recommend": "Yes",
        "additional_comments": "Very happy with the keyboard classes.",
        "contact_preference": "Yes",
        "phone_number": "9123456789",
        "frequency": "Weekly",
        "affected": "Students",
        "digital_tool_help": "Yes",
        "digital_tool_types": ["Mobile App"],
        "user_group": "Both",
        "description": "Suggest WhatsApp progress updates and monthly parent-teacher meetings.",
        "priority": "Medium",
        "status": "In Review",
        "feedback_id": "KFA-2026-100003",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Deepa Krishnan",
        "student_name": "Meera Krishnan",
        "department": "Madambakkam",
        "branch": "Madambakkam",
        "problems": ["Improvement Idea"],
        "feedback_category": "Improvement Idea",
        "star_rating": 4,
        "main_feedback": "The class timings are too fixed. Working parents find it difficult to pick up children at exactly 6 PM. A flexible 30-minute window would be very helpful.",
        "improvement_areas": ["Class Timing", "Communication"],
        "expectations": "Flexible class timing options — especially for working mothers who commute late.",
        "recommend": "Yes",
        "additional_comments": "",
        "contact_preference": "No",
        "phone_number": "",
        "frequency": "Daily",
        "affected": "Students",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Students",
        "description": "Request flexible pickup timings for working parents.",
        "priority": "Medium",
        "status": "New",
        "feedback_id": "KFA-2026-100004",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Rajesh Pillai",
        "student_name": "Dev Pillai",
        "department": "Guduvancheri",
        "branch": "Guduvancheri",
        "problems": ["Complaint"],
        "feedback_category": "Complaint",
        "star_rating": 3,
        "main_feedback": "The parking area is too small. On busy days like Saturdays, parents are double-parking on the road which is dangerous. More space or a proper system is needed.",
        "improvement_areas": ["Parking", "Facilities"],
        "expectations": "A parking slot management system or an expanded parking area would be appreciated.",
        "recommend": "Maybe",
        "additional_comments": "Saturday batch is the most crowded. Please manage it better.",
        "contact_preference": "Yes",
        "phone_number": "9988776655",
        "frequency": "Weekly",
        "affected": "Everyone",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Both",
        "description": "Parking is a serious issue on Saturdays. Parents double-park on the road.",
        "priority": "High",
        "status": "In Review",
        "feedback_id": "KFA-2026-100005",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    },
    {
        "name": "Anitha Selvam",
        "student_name": "Riya Selvam",
        "department": "Madambakkam",
        "branch": "Madambakkam",
        "problems": ["Appreciation"],
        "feedback_category": "Appreciation",
        "star_rating": 5,
        "main_feedback": "My daughter loves coming to KFA every day. The teachers are so kind and encouraging. The way they teach is very different from school — it's fun and structured at the same time.",
        "improvement_areas": ["Events"],
        "expectations": "Please organise more student concerts and competitions. Children need exposure and a platform to perform.",
        "recommend": "Yes",
        "additional_comments": "Thank you to all the teachers and management for the wonderful work!",
        "contact_preference": "No",
        "phone_number": "",
        "frequency": "Occasionally",
        "affected": "Students",
        "digital_tool_help": "No",
        "digital_tool_types": [],
        "user_group": "Students",
        "description": "Very appreciative of the teaching method and staff. Recommend more concerts.",
        "priority": "Low",
        "status": "Resolved",
        "feedback_id": "KFA-2026-100006",
        "solution_name": None,
        "solution_type": None,
        "solution_status": None,
        "solution_description": None
    }
]
