# Generated by Django 6.0.6 on 2026-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.JSONField(default=list)),
                ('frequency', models.CharField(max_length=50)),
                ('affected', models.CharField(max_length=50)),
                ('digital_tool_help', models.CharField(max_length=50)),
                ('digital_tool_types', models.JSONField(default=list)),
                ('user_group', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='Low', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('solution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('solution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('solution_status', models.CharField(blank=True, max_length=50, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
