# Generated by Django 6.0.6 on 2026-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
