# Generated by Django 6.0.6 on 2026-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_additional_comments_feedback_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='learning_progress',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
